// Zepto AI Cross-Category Assistant - Recommendation & Matcher Engine
import { NON_GROCERY_CATALOG } from "./catalog.js";

export class ZeptoAIMatcher {
  constructor(config = {}) {
    this.stockVerificationRequired = config.stockVerificationRequired ?? true;
    this.sessionNudgeShown = false; // Tracks if a nudge was already presented
    this.lockedRecommendation = null; // Locks recommendation during cart modifications (prevents thrashing)
  }

  // Resets the nudge session state (called on clear cart or place order)
  resetSession() {
    this.sessionNudgeShown = false;
    this.lockedRecommendation = null;
  }

  /**
   * Evaluates cart contents and search intent to return a personalized, non-intrusive recommendation.
   * @param {Object} cartSummary - Summary generated by ZeptoCart
   * @param {string} searchQuery - Current search query from user
   * @returns {Object|null} Recommendation object or null if none should be shown
   */
  getRecommendation(cartSummary, searchQuery = "") {
    // Edge Case E1.1: Cart is empty
    if (!cartSummary || cartSummary.itemsCount === 0) {
      this.resetSession();
      return null;
    }

    // If recommendation is already in the cart, unlock/reset so a new one or nothing can be recommended
    if (this.lockedRecommendation && cartSummary.itemIds.includes(this.lockedRecommendation.id)) {
      this.lockedRecommendation = null;
      this.sessionNudgeShown = false;
    }

    // Edge Case E2.1: Lock recommendation once shown to prevent cart thrashing flash
    if (this.lockedRecommendation) {
      return this.lockedRecommendation;
    }

    let selectedItem = null;
    const cleanSearchQuery = searchQuery.trim().toLowerCase();

    // Helper: Checks if item is in cart (Edge Case E1.2)
    const isAlreadyInCart = (item) => cartSummary.itemIds.includes(item.id);

    // Helper: Checks if item has stock (Edge Case E2.3)
    const hasStock = (item) => !this.stockVerificationRequired || item.stock_count > 0;

    // --- STRATEGY 1: ACTIVE SEARCH INTENT MATCHING (Edge Case E1.3) ---
    if (cleanSearchQuery.length > 0) {
      selectedItem = NON_GROCERY_CATALOG.find(item => {
        if (isAlreadyInCart(item) || !hasStock(item)) return false;
        
        // Match query terms against search_intent array
        return item.trigger_rule.search_intent.some(term => 
          cleanSearchQuery.includes(term) || term.includes(cleanSearchQuery)
        );
      });
    }

    // --- STRATEGY 2: CONTEXTUAL CATEGORY / ITEM MATCHING ---
    if (!selectedItem) {
      selectedItem = NON_GROCERY_CATALOG.find(item => {
        if (isAlreadyInCart(item) || !hasStock(item)) return false;

        const rule = item.trigger_rule;

        // A. Match specific item cross-sells
        if (rule.cart_items && rule.cart_items.some(id => cartSummary.itemIds.includes(id))) {
          return true;
        }

        // B. Match general category affinities
        if (rule.cart_categories && rule.cart_categories.some(cat => cartSummary.categories.includes(cat))) {
          return true;
        }

        return false;
      });
    }

    // --- STRATEGY 3: GENERIC / HIGH-MARGIN FALLBACK (Edge Case E1.4) ---
    if (!selectedItem) {
      selectedItem = NON_GROCERY_CATALOG.find(item => {
        // Find Shalimar Garbage Bags or Himalaya Baby Wipes as high-margin utility fallbacks
        return !isAlreadyInCart(item) && hasStock(item) && 
          (item.id === "ng_home_1" || item.id === "ng_baby_1");
      });
    }

    // Finalize recommendation if a candidate was matched
    if (selectedItem) {
      const recommendation = {
        item: selectedItem,
        hook: selectedItem.trigger_rule.routine_hook,
        category: selectedItem.category
      };

      // Set the lock so subsequent cart additions/subtractions in this session don't flash a new suggestion
      this.lockedRecommendation = recommendation;
      this.sessionNudgeShown = true;
      return recommendation;
    }

    return null;
  }
}
